// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoConfigGet() {
  return window['go']['main']['App']['GoConfigGet']();
}

export function GoConfigUpdate(arg1, arg2) {
  return window['go']['main']['App']['GoConfigUpdate'](arg1, arg2);
}

export function GoContainers() {
  return window['go']['main']['App']['GoContainers']();
}

export function GoDeleteContainer(arg1) {
  return window['go']['main']['App']['GoDeleteContainer'](arg1);
}

export function GoDeleteImage(arg1, arg2) {
  return window['go']['main']['App']['GoDeleteImage'](arg1, arg2);
}

export function GoDeleteNetwork(arg1) {
  return window['go']['main']['App']['GoDeleteNetwork'](arg1);
}

export function GoDeleteVolume(arg1) {
  return window['go']['main']['App']['GoDeleteVolume'](arg1);
}

export function GoExecContainer(arg1) {
  return window['go']['main']['App']['GoExecContainer'](arg1);
}

export function GoFilesContainer(arg1, arg2) {
  return window['go']['main']['App']['GoFilesContainer'](arg1, arg2);
}

export function GoImages() {
  return window['go']['main']['App']['GoImages']();
}

export function GoInspectContainer(arg1) {
  return window['go']['main']['App']['GoInspectContainer'](arg1);
}

export function GoLogsContainer(arg1) {
  return window['go']['main']['App']['GoLogsContainer'](arg1);
}

export function GoNetworks() {
  return window['go']['main']['App']['GoNetworks']();
}

export function GoOpenCompose(arg1) {
  return window['go']['main']['App']['GoOpenCompose'](arg1);
}

export function GoOpenConsole(arg1, arg2) {
  return window['go']['main']['App']['GoOpenConsole'](arg1, arg2);
}

export function GoPauseContainer(arg1) {
  return window['go']['main']['App']['GoPauseContainer'](arg1);
}

export function GoRestartContainer(arg1) {
  return window['go']['main']['App']['GoRestartContainer'](arg1);
}

export function GoStartContainer(arg1) {
  return window['go']['main']['App']['GoStartContainer'](arg1);
}

export function GoStatsContainer(arg1) {
  return window['go']['main']['App']['GoStatsContainer'](arg1);
}

export function GoStatsContainers() {
  return window['go']['main']['App']['GoStatsContainers']();
}

export function GoStopContainer(arg1) {
  return window['go']['main']['App']['GoStopContainer'](arg1);
}

export function GoUnpauseContainer(arg1) {
  return window['go']['main']['App']['GoUnpauseContainer'](arg1);
}

export function GoVolumes() {
  return window['go']['main']['App']['GoVolumes']();
}
