// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoContainers() {
  return window['go']['main']['App']['GoContainers']();
}

export function GoDeleteContainer(arg1) {
  return window['go']['main']['App']['GoDeleteContainer'](arg1);
}

export function GoInspectContainer(arg1) {
  return window['go']['main']['App']['GoInspectContainer'](arg1);
}

export function GoLogsContainer(arg1) {
  return window['go']['main']['App']['GoLogsContainer'](arg1);
}

export function GoPauseContainer(arg1) {
  return window['go']['main']['App']['GoPauseContainer'](arg1);
}

export function GoRestartContainer(arg1) {
  return window['go']['main']['App']['GoRestartContainer'](arg1);
}

export function GoStartContainer(arg1) {
  return window['go']['main']['App']['GoStartContainer'](arg1);
}

export function GoStatsContainer() {
  return window['go']['main']['App']['GoStatsContainer']();
}

export function GoStopContainer(arg1) {
  return window['go']['main']['App']['GoStopContainer'](arg1);
}

export function GoUnpauseContainer(arg1) {
  return window['go']['main']['App']['GoUnpauseContainer'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
